settings:
  default-mob-type: ZOMBIE
  default-spawn-count: 5
  default-respawn-delay: 30
  restart-interval: 10
  mob-containment-enabled: true
  passive-mobs-attack-players: true
  health-update-interval: 10

messages:
  prefix: "&8[&bXMobGeneration&8] &7"
  area-created: "&aSpawn area %name% has been created successfully!"
  area-deleted: "&cSpawn area %name% has been deleted!"
  area-not-found: "&cSpawn area %name% does not exist!"
  area-exists: "&cA spawn area with that name already exists!"
  area-configured: "&aSpawn area %name% has been configured!"
  invalid-mob-type: "&cInvalid mob type specified!"
  invalid-mythicmob-type: "&cInvalid MythicMob type specified!"
  mythicmobs-not-installed: "&cMythicMobs is not installed on this server!"
  invalid-numbers: "&cInvalid number format! Please use valid numbers."
  no-selection: "&cYou must make a WorldEdit selection first!"
  selection-error: "&cError getting WorldEdit selection!"
  usage-createarea: "&cUsage: /xmg create <name>"
  usage-deletearea: "&cUsage: /xmg deletearea <name>"
  usage-configarea: "&cUsage: /xmg config <name> <mobType|mythic:mobType> <spawnCount> <respawnDelay>"
  usage-setmobnames: "&cUsage: /xmg setmobnames <areaname> <mobname>"
  usage-mobconfig: "&cUsage: /xmg mobconfig <areaname> <health> <damage> <level>"
  mobname-set: "&aMob name for area %name% has been set to '%mobname%'!"
  mobconfig-set: "&aMob stats for area %name% updated: Health: %health%, Damage: %damage%, Level: %level%"
  pos1-set: "&aPosition 1 set!"
  pos2-set: "&aPosition 2 set!"
  max-areas-reached: "&cMaximum number of areas (45) has been reached!"
  restart-warning: "&e&lAll mob areas will be reset in %minutes% minute(s)!"
  restart-complete: "&a&lAll mob areas have been successfully reset!"
  invalid-restart-interval: "&cRestart interval must be greater than 1 minute! Using default value of 10 minutes."
  boss-pos-set: "&aBoss spawn position set for area %name%!"
  pos-not-in-area: "&cThis position is not inside any spawn area!"
  no-boss-areas: "&cNo boss areas found!"
  not-boss-area: "&cThis area is not a boss area!"
  no-boss-spawn: "&cNo boss spawn point set for this area!"
  boss-configured: "&aBoss area %name% has been configured!"
  usage-configboss: "&cUsage: /xmg configboss <name> <mobType|mythic:mobType> <respawnDelay>"
  usage-setxp: "&cUsage: /xmg xp <area> <amount>"
  invalid-xp-amount: "&cXP amount must be 0 or greater!"
  xp-set: "&aXP amount for area %name% set to %amount%!"
  xp-earned: "&a+%amount% XP"
  usage-levelrange: "&cUsage: /xmg levelrange <area> <minLevel> <maxLevel>"
  level-range-set: "&aLevel range for area %name% set to %min%-%max%!"
  usage-proximity: "&cUsage: /xmg proximity <area> <true|false> <range>"
  proximity-set: "&aPlayer proximity for area %name% %enabled% with range %range% blocks!"
